# Generated by Django 2.2.5 on 2019-09-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('genre', models.CharField(max_length=50)),
                ('directors', models.CharField(max_length=100)),
                ('stars', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
